# data_visualization
# 
# Data exploration
# 

rm(list = ls())
library(tidyverse)
library(ggplot2)
library(readr)

age.col.types <- cols(ID = col_integer(),
                      Specimen = col_character(),
                      Age = col_double(),
                      IsAnalysisQuality = col_factor(levels = c("Y", "N")),
                      EstimationMethod = col_factor(),
                      AgeReader1 = col_double(), 
                      ReaderID1 = col_integer(),
                      AgeReader2 = col_double(),
                      ReaderID2 = col_integer(),
                      AgeReader3 = col_double(),
                      ReaderID3 = col_integer(),
                      AgeReader4 = col_double(),
                      ReaderID4 = col_integer(),
                      EditDate = col_datetime(),
                      EditUser = col_character(),
                      RecordCreationDate= col_datetime())

table.Age <- read_csv(file = "Data/tbl_Age_2026-05-11.csv",
                        col_types = age.col.types)


morph.col.types <- cols(Specimen = col_character(),
                        TotalLength_LAB = col_double(),
                        IsStandardTL_LAB = col_factor(levels = c("Y", "N", "y", "n")),
                        TotalLength_FIELD = col_double(),
                        IsStandardTL_FIELD = col_factor(levels = c("Y", "N", "y", "n")),
                        IsAltMeasurementDeviceUsed = col_factor(levels = c("Y", "N", "y", "n")),
                        Spotter_Color = col_integer(),
                        Spinner_Morph = col_integer(),
                        Spinner_Cape = col_integer(),
                        Spinner_Fin = col_integer(),
                        Spinner_Belly = col_integer(),
                        STOANUS = col_double(),
                        STOGENSLIT = col_double(),
                        STOUMBIL = col_double(),
                        STOTHRGROO = col_double(),
                        STODOFINTIP = col_double(),
                        STOANTDOR = col_double(),
                        STOFLIPPER = col_double(),
                        STOEAR = col_double(),
                        STOEYE = col_double(),
                        STOGAPE = col_double(),
                        STOBLOHOLE = col_double(),
                        STOMELAPEX = col_double(),
                        ETOEAR = col_double(),
                        ETOGAPE = col_double(),
                        ETOBLOHL_L = col_double(),
                        ETOBLOHL_R = col_double(),
                        BLOHL_LGTH = col_double(),
                        BLOHLWDTH = col_double(),
                        DIAM_EAR = col_character(),
                        HEAD_DIAM = col_double(),
                        LGTH_EOP = col_double(),
                        ROSTWIDTH = col_double(),
                        PROJECTUP = col_character(),
                        PROJECTLOW = col_character(),
                        THROATGROOVE_N = col_integer(),
                        LGTH_GROO = col_double(),
                        FLIPLGTH_A = col_double(),
                        FLIPLGTH_P = col_double(),
                        FLIPWIDTH = col_double(),
                        LGTHMAMS_R = col_double(),
                        LGTHMAMS_L = col_double(),
                        MAMMSLIT_N = col_integer(),
                        LGTHGENSLI = col_double(),
                        LGTHANASLI = col_double(),
                        PERILGTH = col_double(),
                        FLUKWDTH = col_double(),
                        FLUKDPTH_L = col_double(),
                        FLUKDPTH_N = col_double(),
                        FLUKNTDPTH = col_double(),
                        DORFNHGT = col_double(),
                        DORFNBLGTH = col_double(),
                        GATEYE = col_double(),
                        GAAXILLA = col_double(),
                        GIRTHMAX = col_double(),
                        GATANUS = col_double(),
                        GMIDANTONT = col_double(),
                        HGTSMPL = col_double(),
                        THICKSMPL = col_double(),
                        BLUBTHIK_D = col_double(),
                        BLUBTHIK_L = col_double(),
                        BLUBTHIK_V = col_double(),
                        BLUBTHIK_C = col_double(),
                        BlubberCompData = col_factor(levels = c("Y", "N", "y", "n")),
                        Pinn_CurvilinearLength = col_double(),
                        Pinn_FlipperLn_ForeAnt = col_double(),
                        Pinn_FlipperLn_HindAnt = col_double(),
                        EditDate = col_datetime(),
                        EditUser = col_character(),
                        RecordCreationDate = col_datetime())

table.Morph <- read_csv(file = "Data/tbl_Morphology_2026-05-11.csv",
                      col_types = morph.col.types)

animal.col.types <- cols(Specimen = col_character(),
                        OriginID = col_integer(),
                        IsSWFSC = col_factor(levels = c("Y", "N", "y", "n")),
                        IsDataSheet = col_factor(levels = c("Y", "N", "y", "n")),
                        Cruise = col_character(),
                        Cruise_Set = col_character(),
                        Year = col_integer(),
                        Month = col_integer(),
                        Day = col_integer(),
                        Latitude = col_double(),
                        Latitude_Precision = col_double(),
                        Latitude_Precision_Unit = col_character(),
                        Longitude = col_double(),
                        Longitude_Precision = col_double(),
                        Longitude_Precision_Unit = col_character(),
                        CityID = col_integer(),
                        CountyID = col_integer(),
                        StateID = col_integer(),
                        CountryID = col_integer(),
                        SpeciesID = col_character(),
                        SpDeterminationID = col_character(),
                        Sex = col_factor(levels = c("F", "M", "U", "f", "m", "u")),
                        Adrenals_Coll = col_character(),
                        Genetics_Biopsy_Coll = col_character(),
                        Blood_Coll = col_character(),
                        Blubber_Coll = col_character(),
                        Brain_Coll = col_character(),
                        Carcass_Coll = col_character(),
                        Feces_Coll = col_character(),
                        Fetus_Coll = col_character(),
                        FetusGenetics_Coll = col_character(),
                        Gonad_Coll = col_character(),
                        Head_Coll = col_character(),
                        Histo_Coll = col_character(),
                        Kidney_Coll = col_character(),
                        Liver_Coll = col_character(),
                        Lung_Coll = col_character(),
                        Morphometry_Coll = col_character(),
                        Muscle_Coll = col_character(),
                        Photos_Coll = col_character(),
                        Radiology_Coll = col_character(),
                        Skeleton_Coll = col_character(),
                        Spleen_Coll = col_character(),
                        Stomach_Coll = col_character(),
                        Teeth_Coll = col_character(),
                        Urine_Coll = col_character(),
                        Other_Coll = col_character(),
                        EditDate = col_datetime(),
                        EditUser = col_character(),
                        RecordCreationDate = col_datetime())


table.Animal <- read_csv(file = "Data/tbl_Animal_2026-05-11.csv",
                        col_types = animal.col.types)
